  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and redeploy containers
        run: |
          ssh admin@chiara.carlino.takima.cloud "
          docker pull ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest &&
          docker pull ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest &&
          docker pull ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest &&

          # Stop old containers if exist
          docker stop api-student || true
          docker rm api-student || true

          docker stop db-student || true
          docker rm db-student || true

          docker stop httpd || true
          docker rm httpd || true

          # Run new containers
          docker run -d --name db-student -e POSTGRES_PASSWORD=mysecretpassword ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest
          docker run -d --name api-student -p 8080:8080 --link db-student ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          docker run -d --name httpd -p 80:80 ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
          "


