name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H lucille.finet.takima.cloud >> ~/.ssh/known_hosts
          
      - name: Test SSH connection
        run: ssh -v admin@lucille.finet.takima.cloud "echo 'SSH connection successful'"

      - name: Login to Docker Hub on remote server
        run: |
          ssh admin@lucille.finet.takima.cloud "docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Deploy to remote server
        run: |
          ssh admin@lucille.finet.takima.cloud '
            # Check Docker status
            docker info || exit 1

            # Create network if it doesn't exist
            docker network create app-network || true

            # Stop and remove old containers
            docker stop simple-api db httpd || true
            docker rm simple-api db httpd || true

            # Pull latest images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest

            # Start database
            docker run -d --name db \
              --network app-network \
              -e POSTGRES_DB=db \
              -e POSTGRES_USER=usr \
              -e POSTGRES_PASSWORD=pwd \
              ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest

            # Wait for database to be ready
            sleep 10

            # Start API
            docker run -d --name simple-api \
              --network app-network \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db \
              -e SPRING_DATASOURCE_USERNAME=usr \
              -e SPRING_DATASOURCE_PASSWORD=pwd \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

            # Start HTTP server
            docker run -d --name httpd \
              --network app-network \
              -p 80:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest

            # Verify containers are running
            docker ps -a
          '


