  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Clean up existing containers
        run: |
          docker stop api-student db-student httpd || true
          docker rm api-student db-student httpd || true
          docker network rm app-network || true

      - name: Create network
        run: docker network create app-network

      - name: Deploy database
        run: |
          docker run -d --name db-student \
            --network app-network \
            -e POSTGRES_DB=db \
            -e POSTGRES_USER=usr \
            -e POSTGRES_PASSWORD=pwd \
            ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest

          # Wait for database to be ready
          sleep 10

      - name: Deploy API
        run: |
          docker run -d --name api-student \
            --network app-network \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://db-student:5432/db \
            -e SPRING_DATASOURCE_USERNAME=usr \
            -e SPRING_DATASOURCE_PASSWORD=pwd \
            -p 8080:8080 \
            ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

      - name: Deploy HTTP server
        run: |
          docker run -d --name httpd \
            --network app-network \
            -p 80:80 \
            ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest


