deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and redeploy containers
        run: |
          ssh admin@lucille.finet.takima.cloud "
          docker pull ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest &&
          docker pull ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest &&
          docker pull ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest &&

          # Stop old containers if exist
          docker stop simple-api || true
          docker rm simple-api || true

          docker stop db || true
          docker rm db || true

          docker stop httpd || true
          docker rm httpd || true

          # Run new containers
          docker run -d --name db -e POSTGRES_PASSWORD=mysecretpassword ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest
          docker run -d --name simple-api -p 8080:8080 --link db-student ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          docker run -d --name httpd -p 80:80 ${{ env.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
          "


