name: Deploy with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Deploy with Docker Compose
        run: |
          # Stop any running containers
          docker compose down || true
          
          # Pull latest images
          docker compose pull
          
          # Start services
          docker compose up -d

      - name: Check deployment status
        run: |
          echo "Waiting for services to start..."
          sleep 10
          docker compose ps
          docker compose logs


