name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # JDK Temurin recommandé par GitHub
          java-version: '21'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # fourni automatiquement par GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # ton token secret SonarCloud
        run: 
          mvn -B verify sonar:sonar -Dsonar.projectKey=lucille678_devops_tp2 -Dsonar.organization=lucille678 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml
